# Generated by Django 4.0.2 on 2022-03-14 14:42

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': [django.db.models.functions.text.Upper('name')]},
        ),
        migrations.RemoveField(
            model_name='action',
            name='user',
        ),
    ]
