# Generated by Django 4.0.2 on 2022-03-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_action_remove_task_description_task_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='action',
        ),
        migrations.AddField(
            model_name='action',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.task'),
        ),
    ]
