# Generated by Django 4.0.2 on 2022-03-06 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_task_action_action_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='base.task'),
        ),
    ]
