# Generated by Django 4.0.2 on 2022-03-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_action_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='ended_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='action',
            name='started_at',
            field=models.TimeField(),
        ),
    ]
